### ISSUE TITLE
Steemia app v0.0.5||After entering in a user's profile from that user's post does not show any info of the profile. 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#111] opened 2018-07-13 20:48 UTC
## Expected Behavior
After entering in any user's profile from his/her post must show all the info of the user's profile. 

## Actual Behavior
After entering in someone's profile from their own posts doesn't show any info of their profile. 

## Steps to Reproduce the Problem

  1. Start Steemia app v0.0.5 then login and enter in any post from the home screen of Steemia app. 
  2. At the top left of the post you will see user's icon who submit that specific post you've entered. 
  3. Then click on the user's profile icon to see the profile info. 
 4. Note that after entering in the post owners profile from his/her own post doesn't show any info of the profile and app says that"There are no more post to load". 

## Specifications

  - Version: Steemia v0.0.5
  - Platform: Android 7.0 
  - Recorded video : https://vimeo.com/279915979

**Comment by jayserdny** [comment] 2018-07-14 00:42
Hello,

I will close this one in favor of #106 which is basically the same issue. This behavior is caused by the bug reported in #106.

Thanks :)

**Closed as completed by jayserdny** 2018-07-14 00:42 UTC
