### ISSUE TITLE
Steemia app v0.0.5 doesn't show comment owners profile 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#112] opened 2018-07-14 06:58 UTC
## Expected Behavior
After entering a post commenter profile must be shown. 

## Actual Behavior
User can't see the commenter profile. Because after clicking on the profile icon or commenter name profile doesn't load. 

## Steps to Reproduce the Problem

  1. Start Steemia app v0.0.5 and enter in a post which already have some comments. 
  2. Then go to the bottom of the post to see the comments. 
  3. In the left side of a comment, commenter name and icon shows. 
 4. Click on the commenter name or icon to see the profile. 
 5. Note that the commenter profile doesn't load. 

## Specifications

  - Version: Steemia v0.0.5 
  - Platform: Android 7.0 
  - Recorded video: https://vimeo.com/279964856

**Comment by jayserdny** [comment] 2018-07-14 13:14
Hello,

Thanks for your report. Your report is reporting the same behavior of #106 even if it is from different place but still ends up at the same page. This is caused by the report of #106 so I will close this one in favor of #106.

**Closed as completed by jayserdny** 2018-07-14 13:14 UTC
